---

- name: Install smartmontools
  yum:
    name: smartmontools
    state: present

- name: Copy the smartd config over
  template:
    src: smartd.conf
    dest: /etc/smartmontools/smartd.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify: Restart smartd
