---

- name: Add variables
  include_vars: main.yml

- name: Install smartmontools
  yum:
    name: smartmontools
    state: present

- name: Copy the smartd config over
  template:
    src: smartd.conf
    dest: /etc/smartmontools/smartd.conf
    backup: yes
    # owner: "{{whoami}}"
    # group: "{{whoami}}"
    # mode:  0644
